In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('spam.csv')

In [3]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [5]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [6]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
from sklearn.model_selection import train_test_split

C:\Users\Amir Hamza\Anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [8]:
X_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
x_train_count = v.fit_transform(X_train.values)
x_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [10]:
v.get_feature_names_out().shape

(7734,)

In [11]:
dir(v)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',

In [12]:
v.vocabulary_

{'gud': 3255,
 'mrng': 4593,
 'dear': 2198,
 'hav': 3346,
 'nice': 4755,
 'day': 2185,
 'he': 3358,
 'fucking': 3023,
 'chickened': 1793,
 'out': 4992,
 'messaged': 4438,
 'me': 4386,
 'would': 7598,
 'be': 1285,
 'late': 4000,
 'and': 969,
 'woould': 7575,
 'buzz': 1600,
 'then': 6821,
 'didn': 2311,
 'hear': 3369,
 'word': 7577,
 'from': 3010,
 'him': 3426,
 'phony': 5174,
 '350': 446,
 'award': 1181,
 'todays': 6929,
 'voda': 7307,
 'numbers': 4843,
 'ending': 2585,
 'xxxx': 7649,
 'are': 1059,
 'selected': 5983,
 'to': 6922,
 'receive': 5614,
 'if': 3587,
 'you': 7697,
 'have': 3349,
 'match': 4357,
 'please': 5232,
 'call': 1620,
 '08712300220': 102,
 'quoting': 5528,
 'claim': 1832,
 'code': 1890,
 '3100': 439,
 'standard': 6433,
 'rates': 5563,
 'app': 1028,
 'its': 3744,
 'part': 5075,
 'of': 4879,
 'checking': 1769,
 'iq': 3715,
 'where': 7474,
 'at': 1131,
 'were': 7454,
 'hungry': 3539,
 'too': 6960,
 'bring': 1521,
 'it': 3737,
 'got': 3189,
 'ok': 4902,
 'which': 7479,
 'y

In [13]:
v.get_feature_names_out()[6564]

'subscriptn3gbp'

In [14]:
x_train_count = x_train_count.toarray()
x_train_count[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [15]:
np.where(x_train_count[0]!=0)

(array([2185, 2198, 3255, 3346, 4593, 4755], dtype=int64),)

In [16]:
x_train_count[0][865]

0

In [17]:
v.get_feature_names_out()[865]

'against'

In [18]:
from sklearn.naive_bayes import MultinomialNB
model= MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [19]:
X_test_count = v.transform(x_test)

In [20]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_count)

In [21]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       969
           1       0.97      0.95      0.96       146

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [22]:
emails = [
    'Hey nohan, can we get together to watch football game tomarrow',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [23]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
    
])

In [24]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [2]:
y_pred = clf.predict(x_test)

print(classification_report(y_test,y_pred))


NameError: name 'clf' is not defined